name: Build and Package Windows Installer

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  windows_installer_build:
    name: Build Windows App
    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.2

    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Force -Scope CurrentUser
      shell: pwsh

    - name: Build executable
      run: |
        ps2exe -InputFile "MylesMattlockWinTool.ps1" -OutputFile "MylesMattlockWinTool.exe" -IconFile "MM.ico" -version '1.0.0'
      shell: pwsh

    - name: Upload executable artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: MylesMattlockWinTool-Exe
        path: MylesMattlockWinTool.exe

  create_release:
    name: Create Release
    needs: windows_installer_build
    if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download executable artifact
      uses: actions/download-artifact@v8.0.1
      with:
        name: MylesMattlockWinTool-Exe

    - name: Create GitHub release
      uses: softprops/action-gh-release@v3.0.2
      with:
        tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'beta-latest' }}
        files: MylesMattlockWinTool.exe
        draft: false
        prerelease: ${{ github.ref == 'refs/heads/main' || contains(github.ref_name, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}