name: Build and Package Windows Installer

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  windows_installer_build:
    name: Build Windows App
    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.2

    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Force -Scope CurrentUser
      shell: pwsh

    - name: Build executable
      run: |
        ps2exe -InputFile "MylesMattlockWinTool.ps1" -OutputFile "MylesMattlockWinTool.exe" -IconFile "MM.ico" -version '1.0.0'
      shell: pwsh

    - name: Upload executable artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: MylesMattlockWinTool-Exe
        path: MylesMattlockWinTool.exe